### ISSUE TITLE
Bug in IE?

### ISSUE THREAD

**Issue by SVVredeburg** [ryancookdev/canvas-chess#2]
Hi there,
First I would like to thank you for setting up this great framework. So simple to use with great results.
However, in Internet Explorer 11 people are claiming not to see the moves. Indeed, also at [Angry Bishop](http://angrybishop.net/5-proofs-opponent-cheating-online/) this can be seen. Weirdly, pressing Ctrl+F5 (removing cache) works... sometimes! 
Is this something you've encountered before and what would you advise? Not to use IE altogether?

Many thanks in advance,
Bert Hollander

**Comment by ryancookdev** [comment]
Hi Bert,
I'm happy to hear that you like my project. Thanks for messaging me and for reporting this bug. From your description, it sounds like a problem I had fixed a while back, but it's possible I didn't fix it completely for every browser. I will see if I can recreate the issue on my machine in IE 11 and get it fixed for you.
Regards,
Ryan

**Comment by ryancookdev** [comment]
Confirmed, I see the problem you're describing @SVVredeburg on AngryBishop in IE11. I'll try to recreate this locally so I can get it fixed.

**Comment by ryancookdev** [comment]
@SVVredeburg I was unable to duplicate this bug locally. I also checked another site that uses Canvas Chess, and it displays properly on the first load in IE11: http://thechessworld.com/learn-chess/1-openings/768-fighting-the-samisch

It seems likely that the issue is specific to AngryBishop, possibly due to other scripts that are running on the site. It looks like a Wordpress plugin is modifying the script tags (changing them from type javascript to rocketscript). Disabling the plugin might fix the issue, but I'm unable to confirm that.

**Comment by SVVredeburg** [comment]
@ryancookdev Oh, that indeed is the solution! It turned out I had for another part of the site the Google JSapi loaded which apparently interferes. After removing it I wasn't able to reproduce the problem either :-) Thanks for your time!

Bert

**Comment by ryancookdev** [comment]
@SVVredeburg Best of luck with your website!
